apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-value-converting-service_vestfoldfylke_no
      fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/vestfoldfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vestfoldfylke-no/api/intern/value-convertings"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "vestfoldfylke.no":["USER"],
            "vigo.no":["DEVELOPER", "USER"],
            "novari.no":["DEVELOPER", "USER"]
          }
      - op: replace
        path: "/spec/env/4/value"
        value: "vestfoldfylke-no"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/vestfoldfylke-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/vestfoldfylke-no/actuator/prometheus"

    target:
      kind: Application
      name: fint-flyt-value-converting-service

