apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-flyt-value-converting-service
data:
  fint.org-id: 'vlfk.no'
  fint.flyt.resource-server.security.api.internal.authorized-org-ids: 'vlfk.no, vigo.no'
  spring.webflux.base-path: 'beta/vlfk-no'