apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-value-converting-service_mrfylke_no
  fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "mrfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/mrfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/mrfylke-no/api/intern/value-convertings"
      - op: replace
        path: "/spec/env/1/value"
        value: "mrfylke.no, vigo.no"

    target:
      kind: Application
      name: fint-flyt-value-converting-service

