apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-value-converting-service_mrfylke_no
      fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "mrfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/mrfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/mrfylke-no/api/intern/value-convertings"
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.flyt.resource-server.security.api.internal.authorized-org-id-role-pairs-json"
          value: |
            {
              "mrfylke.no":["USER"],
              "vigo.no":["DEVELOPER", "USER"],
              "novari.no":["DEVELOPER", "USER"]
            }
      - op: add
        path: "/spec/env/-"
        value:
         name: "novari.kafka.topic.orgId"
         value: "mrfylke-no"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/mrfylke-no/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/mrfylke-no/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/mrfylke-no/actuator/health/liveness"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/mrfylke-no/actuator/prometheus"

    target:
      kind: Application
      name: fint-flyt-value-converting-service
