apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agderfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-value-converting-service_agderfk_no
  fintlabs.no/org-id: agderfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "agderfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "agderfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/agderfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/agderfk-no/api/intern/value-convertings"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "agderfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }

    target:
      kind: Application
      name: fint-flyt-value-converting-service

