apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-flyt-value-converting-service
data:
  TZ: 'Europe/Oslo'
  JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  fint.flyt.resource-server.security.api.internal.enabled: 'true'